services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    container_name: palworld-server
    restart: unless-stopped
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211
      - PLAYERS=8
      - SERVER_NAME=PongoPal Island
      - SERVER_PASSWORD=${SERVER_PASS}
      - ADMIN_PASSWORD=${SERVER_ADMIN_PASS}
      # - UPDATE_ON_BOOT=false
      # only run this for the 1st time get download the latest version
      - UPDATE_ON_BOOT=True
      - BACKUP_ENABLED=true
      - BACKUP_CRON_EXPRESSION=*/30 * * * *
    volumes:
      - ./palworld:/palworld/
    networks:
      game-net:
        ipv4_address: 172.25.0.5
  playit:
    image: ghcr.io/playit-cloud/playit-agent:1.0
    container_name: playit
    restart: unless-stopped
    environment:
      - SECRET_KEY=${PLAY_IT_SECRET_KEY}
    network_mode: host

networks:
  game-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
